example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('wishlist/', include('wishlist.urls')),
    path('', include('example_app.urls')),
    path('testing/', include('testing_bootstrap.urls'))
]

testing_bootstrap/urls.py
from django.urls import path
from testing_bootstrap.views import show_bootstrap_testing

app_name = 'example_app'

urlpatterns = [
    path('', show_bootstrap_testing, name='show_bootstrap_testing'),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import xml_data #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import register #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import login_user #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import logout_user #sesuaikan dengan nama fungsi yang dibuat
from wishlist.views import show_wishlist_ajax
from wishlist.views import json_data, GetData


app_name = 'wishlist'


urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', xml_data, name='xml'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('json/', json_data, name='json_data'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/get', GetData.as_view(), name='get_data')
]

testing_bootstrap/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

    objects = models.Manager()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

testing_bootstrap/views.py
from django.shortcuts import render

# Create your views here.
def show_bootstrap_testing(request):
    return render(request, 'bootstrap_testing.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import View

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Ajra kun',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):

    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': None,
        'nama': 'Ajra kun',
        'last_login': request.COOKIES['last_login'],
    }

    # if request.is_ajax():
    #     data = data_barang_wishlist
    #     data_serializer = serializers.serialize('json', data)
    #     return JsonResponse(data_serializer, safe=False)
    return render(request, "wishlist_ajax.html", context)

class GetData(View):
    
    def get(self, request, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            barang = BarangWishlist.objects.all()
            barang_serializers = serializers.serialize('json', barang)
            return JsonResponse(barang_serializers, safe=False)
        return JsonResponse({'message' : 'Wrong Validation'})

def xml_data(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def json_data(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')

    context = {'form': form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)  # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist"))  # membuat response
            response.set_cookie('last_login',
                                str(datetime.datetime.now()))  # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
<link rel="stylesheet" href="{% static 'css/tutorial.css' %}">
{% endblock meta %}

{% block content %}
  <div id="header">
    <h1>Hello, world!</h1>
    <h3>This is example app for Django template</h3>
  </div>

  <div id="main">
    <div class="content_section">
        <p class="date">published: 28 September 2022</p>
        <h2><a href="">Tutorial CSS ku</a></h2>
        <p id="content_1">Yay ini tutorial yang gampang!</p>
    </div>
    <div class="content_section">
        <p class="date ">published: 29 September 2022</p>
        <h2><a href="">Tutorial CSS mu</a></h2>
        <p id="content_2">Yay ini tutorial yang mudah!</p>
    </div>
    <div class="content_section">
        <p>published: 30 September 2022</p>
        <h2><a href="">Tutorial CSS semua</a></h2>
        <p id="content_3">Yay ini tutorial yang tidak sulit!</p>
    </div>
  </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

testing_bootstrap/templates/bootstrap_testing.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
<h1>Hello, world!</h1>
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
        integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz"
        crossorigin="anonymous"></script>
</body>
</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
<head>

<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1" name="viewport">
<title>Wishlist</title>
<link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" rel="stylesheet">


</head>

<body>

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">{{nama}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="d-grid gap-2 d-md-block">
  <button class="button2"><a href="{% url 'wishlist:logout' %}">Logout</a></button>
      </div>
  </div>
</nav>




<table class="table table-striped">
    <tr>
        <th><h3>Nama Barang</h3></th>
        <th><h3>Harga Barang</h3></th>
        <th><h3>Deskripsi</h3></th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th>{{barang.nama_barang}}</th>
        <th>{{barang.harga_barang}}</th>
        <th>{{barang.deskripsi}}</th>
    </tr>
    {% endfor %}
</table>
<h5>Sesi terakhir login: {{ last_login }}</h5>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
</body>

wishlist/templates/wishlist_ajax.html
{% load static %}


<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!--    <script>-->
<!--$("btn").click(function(){-->
<!--fetch(URL, {-->
<!--    headers:{-->
<!--        'Accept': 'application/json',-->
<!--        'X-Requested-With': 'XMLHttpRequest', //Necessary to work with request.is_ajax()-->
<!--    },-->
<!--})-->
<!--.then(response => {-->
<!--    alert("hello world!");-->
<!--    return response.json() //Convert response to JSON-->
<!--})-->
<!--.then(data => {-->
<!--    //Perform actions with the response data from the view-->
<!--})-->
<!--}-->
<!--</script>-->

<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1" name="viewport">
<title>Wishlist</title>
<!--<link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"-->
<!--      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" rel="stylesheet">-->


</head>

<body>

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">{{nama}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="d-grid gap-2 d-md-block">
  <button class="button2"><a href="{% url 'wishlist:logout' %}">Logout</a></button>
      </div>
  </div>
</nav>




<table class="table table-striped">
    <tr>
        <th><h3>Nama Barang</h3></th>
        <th><h3>Harga Barang</h3></th>
        <th><h3>Deskripsi</h3></th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th>{{barang.nama_barang}}</th>
        <th>{{barang.harga_barang}}</th>
        <th>{{barang.deskripsi}}</th>
    </tr>
    {% endfor %}
</table>
<div class="col-12 text-center">
                    
    <div class="content-data mt-4" data-url="{% url 'wishlist:get_data' %}">Data di sini</div>
    <button class="btn btn-primary btn-get-data">Get JSON data from Django</button>
</div>
</div>
</div>
<div class="last_login">
<h5>Sesi terakhir login: {{ last_login }}</h5>
</div>
</div>


{% block scripts %}
<script>
    $('.btn-get-data').on('click', function(){
        $.ajax({
            url: $('.content-data').data('url'),
            type: 'GET',
            datatype: 'json',
            success: function(resp){
                var html = '';
                $(resp).each(function(index, value) {
                html += "<tr><td>" + value.nama_barang + "</td><td>" + value.harga_barang + "</td><td>" + value.deskripsi + "</td><td>"
                })
                $(".table-striped").append(html)
            },
            error: function(resp){
                console.log('something went wrong');
            },
        });
    });
</script>
{% endblock scripts %}
</body>